//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdapterDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataItem
    {
        public Nullable<System.DateTime> Created { get; set; }
        public int Id { get; set; }
        public int BusinessId { get; set; }
        public int LineId { get; set; }
        public int ServiceId { get; set; }
        public int AnalyticId { get; set; }
        public int QueueId { get; set; }
        public string Name { get; set; }
        public string Verification { get; set; }
        public Nullable<System.DateTime> Serviced { get; set; }
        public string ServicedByName { get; set; }
        public Nullable<int> ServicedById { get; set; }
        public Nullable<System.DateTime> Called { get; set; }
        public string CalledByName { get; set; }
        public Nullable<int> CalledById { get; set; }
        public Nullable<System.DateTime> Entered { get; set; }
        public int BatchId { get; set; }
        public Nullable<int> WaitTimeSec { get; set; }
        public Nullable<int> ServiceTimeSec { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Business Business { get; set; }
        public virtual Employee ServicingEmployee { get; set; }
        public virtual Employee CallingEmployee { get; set; }
        public virtual Line Line { get; set; }
    }
}
