//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdapterDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdapterDbEntities : DbContext
    {
        public AdapterDbEntities()
            : base("name=AdapterDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Batch> Batch { get; set; }
        public virtual DbSet<ConfigItem> ConfigItem { get; set; }
        public virtual DbSet<UserSignupTicket> UserSignupTicket { get; set; }
        public virtual DbSet<BusinessMember> BusinessMember { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeLine> EmployeeLine { get; set; }
        public virtual DbSet<DataItem> DataItem { get; set; }
        public virtual DbSet<EmployeeStats> EmployeeStats { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
